/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetQuoteRouteImport } from './routes/get-quote'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AdvertisingRatesRouteImport } from './routes/advertising-rates'
import { Route as AdvertisingPackagesRouteImport } from './routes/advertising-packages'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const GetQuoteRoute = GetQuoteRouteImport.update({
  id: '/get-quote',
  path: '/get-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRatesRoute = AdvertisingRatesRouteImport.update({
  id: '/advertising-rates',
  path: '/advertising-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingPackagesRoute = AdvertisingPackagesRouteImport.update({
  id: '/advertising-packages',
  path: '/advertising-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising-packages': typeof AdvertisingPackagesRoute
  '/advertising-rates': typeof AdvertisingRatesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/get-quote': typeof GetQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising-packages': typeof AdvertisingPackagesRoute
  '/advertising-rates': typeof AdvertisingRatesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/get-quote': typeof GetQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising-packages': typeof AdvertisingPackagesRoute
  '/advertising-rates': typeof AdvertisingRatesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/get-quote': typeof GetQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertising-packages'
    | '/advertising-rates'
    | '/case-studies'
    | '/contact'
    | '/get-quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertising-packages'
    | '/advertising-rates'
    | '/case-studies'
    | '/contact'
    | '/get-quote'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertising-packages'
    | '/advertising-rates'
    | '/case-studies'
    | '/contact'
    | '/get-quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertisingPackagesRoute: typeof AdvertisingPackagesRoute
  AdvertisingRatesRoute: typeof AdvertisingRatesRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  GetQuoteRoute: typeof GetQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/get-quote': {
      id: '/get-quote'
      path: '/get-quote'
      fullPath: '/get-quote'
      preLoaderRoute: typeof GetQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising-rates': {
      id: '/advertising-rates'
      path: '/advertising-rates'
      fullPath: '/advertising-rates'
      preLoaderRoute: typeof AdvertisingRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising-packages': {
      id: '/advertising-packages'
      path: '/advertising-packages'
      fullPath: '/advertising-packages'
      preLoaderRoute: typeof AdvertisingPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertisingPackagesRoute: AdvertisingPackagesRoute,
  AdvertisingRatesRoute: AdvertisingRatesRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  GetQuoteRoute: GetQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
